services:
  backend:
    build:
      context: ./server
      dockerfile: ./server/Dockerfile
    image: uwgo-backend-image

  client:
    build:
      context: ./client
      dockerfile: ./client/Dockerfile
    depends_on:
      - backend
    image: uwgo-frontend-image
    ports:
      - "3000:80"
    deploy:
      restart_policy:
        condition: on-failure

